// HAVE_KQUEUE : BUILD2_AUTOCONF_LIBC_VERSION

#ifndef BUILD2_AUTOCONF_LIBC_VERSION
#  error BUILD2_AUTOCONF_LIBC_VERSION appears to be conditionally included
#endif

#undef HAVE_KQUEUE

/* Since OpenBSD 2.9, FreeBSD 4.1, NetBSD 2.0, MacOS 10.0.
 */
#if BUILD2_AUTOCONF_OPENBSD_PREREQ(200106) || \
    BUILD2_AUTOCONF_FREEBSD_PREREQ(4, 1)   || \
    BUILD2_AUTOCONF_NETBSD_PREREQ(2, 0)    || \
    BUILD2_AUTOCONF_MACOS_PREREQ(10, 0)
#  define HAVE_KQUEUE 1
#endif
