// HAVE_FUTIMENS : BUILD2_AUTOCONF_LIBC_VERSION

#ifndef BUILD2_AUTOCONF_LIBC_VERSION
#  error BUILD2_AUTOCONF_LIBC_VERSION appears to be conditionally included
#endif

#undef HAVE_FUTIMENS

/* Since Linux/glibc 2.6, FreeBSD 10.3, OpenBSD 5.0, NetBSD 6.0, Mac OS 10.6
 * (2009).
 */
#if BUILD2_AUTOCONF_GLIBC_PREREQ(2, 6)     || \
    BUILD2_AUTOCONF_FREEBSD_PREREQ(10, 3)  || \
    BUILD2_AUTOCONF_OPENBSD_PREREQ(201111) || \
    BUILD2_AUTOCONF_NETBSD_PREREQ(6, 0)    || \
    BUILD2_AUTOCONF_MACOS_PREREQ(10, 6)
#  define HAVE_FUTIMENS 1
#endif
