// HAVE_GETHOSTBYNAME_R_6_ARG : BUILD2_AUTOCONF_LIBC_VERSION

#ifndef BUILD2_AUTOCONF_LIBC_VERSION
#  error BUILD2_AUTOCONF_LIBC_VERSION appears to be conditionally included
#endif

#undef HAVE_GETHOSTBYNAME_R_6_ARG

/* Since Linux/glibc 2.1
 */
#if BUILD2_AUTOCONF_GLIBC_PREREQ(2, 1)
#  define HAVE_GETHOSTBYNAME_R_6_ARG 1
#endif
