// HAVE_DEV_IC_BT8XX_H : BUILD2_AUTOCONF_LIBC_VERSION

#undef HAVE_DEV_IC_BT8XX_H

/* OpenBSD 2.3, FreeBSD 2.2, glibc 2.19, Windows, Solaris
 */
#if BUILD2_AUTOCONF_GLIBC_PREREQ(2, 19) || \
    BUILD2_AUTOCONF_FREEBSD_PREREQ(2, 2) || \
    BUILD2_AUTOCONF_OPENBSD_PREREQ(199805) || \
    BUILD2_AUTOCONF_NETBSD_PREREQ(1, 5)
#  define HAVE_DEV_IC_BT8XX_H 1
#endif
