// HAVE_KCVPIXELFORMATTYPE_422YPCBCR16BIPLANARVIDEORANGE : BUILD2_AUTOCONF_LIBC_VERSION

#ifndef BUILD2_AUTOCONF_LIBC_VERSION
#  error BUILD2_AUTOCONF_LIBC_VERSION appears to be conditionally included
#endif

#undef HAVE_KCVPIXELFORMATTYPE_422YPCBCR16BIPLANARVIDEORANGE

/* 422 YCbCr 16-bit biplanar video range pixel format,
 * typically used for higher bit depth color processing in HDR.
 * Since MacOS 10.13/iOS 11
 */
#if BUILD2_AUTOCONF_MACOS_PREREQ(10, 13)
#  define HAVE_KCVPIXELFORMATTYPE_422YPCBCR16BIPLANARVIDEORANGE 1
#endif
