// HAVE_INTTYPES_H : BUILD2_AUTOCONF_LIBC_VERSION

#ifndef BUILD2_AUTOCONF_LIBC_VERSION
#  error BUILD2_AUTOCONF_LIBC_VERSION appears to be conditionally included
#endif

#undef HAVE_INTTYPES_H

/* Since OpenBSD 3.9, FreeBSD 5.0, NetBSD 5.0, Mac OS X 10.3
 * and glibc 2.2.
 */
#if BUILD2_AUTOCONF_OPENBSD_PREREQ(200601) || \
    BUILD2_AUTOCONF_FREEBSD_PREREQ(2, 3)   || \
    BUILD2_AUTOCONF_NETBSD_PREREQ(5, 0)    || \
    BUILD2_AUTOCONF_MACOS_PREREQ(10, 3)    || \
    BUILD2_AUTOCONF_GLIBC_PREREQ(2, 2)
#  define HAVE_INTTYPES_H 1
#endif
