// HAVE_SYS_SENDFILE_H : BUILD2_AUTOCONF_LIBC_VERSION

#ifndef BUILD2_AUTOCONF_LIBC_VERSION
#  error BUILD2_AUTOCONF_LIBC_VERSION appears to be conditionally included
#endif

#undef HAVE_SYS_SENDFILE_H

/* Since glibc 2.1.
 */
#if BUILD2_AUTOCONF_GLIBC_PREREQ(2, 1)
#  define HAVE_SYS_SENDFILE_H 1
#endif
