// HAVE_KCVIMAGEBUFFERTRANSFERFUNCTION_SMPTE_ST_2084_PQ : BUILD2_AUTOCONF_LIBC_VERSION

#ifndef BUILD2_AUTOCONF_LIBC_VERSION
#  error BUILD2_AUTOCONF_LIBC_VERSION appears to be conditionally included
#endif

#undef HAVE_KCVIMAGEBUFFERTRANSFERFUNCTION_SMPTE_ST_2084_PQ

/* SMPTE ST 2084 PQ (Perceptual Quantizer) transfer function used in HDR10.
 * Since MacOS 10.11/iOS 9
 */
#if BUILD2_AUTOCONF_MACOS_PREREQ(10, 11)
#  define HAVE_KCVIMAGEBUFFERTRANSFERFUNCTION_SMPTE_ST_2084_PQ 1
#endif
