// HAVE_KCVIMAGEBUFFERTRANSFERFUNCTION_ITU_R_2100_HLG : BUILD2_AUTOCONF_LIBC_VERSION

#ifndef BUILD2_AUTOCONF_LIBC_VERSION
#  error BUILD2_AUTOCONF_LIBC_VERSION appears to be conditionally included
#endif

#undef HAVE_KCVIMAGEBUFFERTRANSFERFUNCTION_ITU_R_2100_HLG

/* ITU-R BT.2100 HLG (Hybrid Log-Gamma) transfer function, used in HDR video.
 * Since MacOS 10.13/iOS 11
 */
#if BUILD2_AUTOCONF_MACOS_PREREQ(10, 13)
#  define HAVE_KCVIMAGEBUFFERTRANSFERFUNCTION_ITU_R_2100_HLG 1
#endif
