// HAVE_KCMVIDEOCODECTYPE_HEVCWITHALPHA : BUILD2_AUTOCONF_LIBC_VERSION

#ifndef BUILD2_AUTOCONF_LIBC_VERSION
#  error BUILD2_AUTOCONF_LIBC_VERSION appears to be conditionally included
#endif

#undef HAVE_KCMVIDEOCODECTYPE_HEVCWITHALPHA

/* HEVC (High-Efficiency Video Coding) with Alpha Channel.
 * Since MacOS 10.13/iOS 11
 */
#if BUILD2_AUTOCONF_MACOS_PREREQ(10, 13)
#  define HAVE_KCMVIDEOCODECTYPE_HEVCWITHALPHA 1
#endif
