// HAVE_SYS_TIMERFD_H : BUILD2_AUTOCONF_LIBC_VERSION

#ifndef BUILD2_AUTOCONF_LIBC_VERSION
#  error BUILD2_AUTOCONF_LIBC_VERSION appears to be conditionally included
#endif

#undef HAVE_SYS_TIMERFD_H

/* Since NetBSD 10.0, glibc 2.8.
 */
#if BUILD2_AUTOCONF_NETBSD_PREREQ(10, 0)    || \
    BUILD2_AUTOCONF_GLIBC_PREREQ(2, 8)
#  define HAVE_SYS_TIMERFD_H 1
#endif
