// HAVE_STRTOLL : BUILD2_AUTOCONF_LIBC_VERSION

#ifndef BUILD2_AUTOCONF_LIBC_VERSION
#  error BUILD2_AUTOCONF_LIBC_VERSION appears to be conditionally included
#endif

#undef HAVE_STRTOLL

/* Since ISO C99 (OpenBSD ~2.7, FreeBSD ~4.0, NetBSD ~1.5, Mac OS X ~10.0),
 * glibc 1.90
 */
#if BUILD2_AUTOCONF_OPENBSD_PREREQ(200015) || \
    BUILD2_AUTOCONF_FREEBSD_PREREQ(4, 0)   || \
    BUILD2_AUTOCONF_NETBSD_PREREQ(1, 5)    || \
    BUILD2_AUTOCONF_MACOS_PREREQ(10, 0)    || \
    BUILD2_AUTOCONF_GLIBC_PREREQ(1, 90)
#  define HAVE_STRTOLL 1
#endif
