// HAVE_KCVPIXELFORMATTYPE_444YPCBCR8BIPLANARVIDEORANGE : BUILD2_AUTOCONF_LIBC_VERSION

#ifndef BUILD2_AUTOCONF_LIBC_VERSION
#  error BUILD2_AUTOCONF_LIBC_VERSION appears to be conditionally included
#endif

#undef HAVE_KCVPIXELFORMATTYPE_444YPCBCR8BIPLANARVIDEORANGE

/* 444 YCbCr 8-bit biplanar video range pixel format,
 * commonly used in professional video production.
 * Since MacOS 10.13/iOS 11
 */
#if BUILD2_AUTOCONF_MACOS_PREREQ(10, 13)
#  define HAVE_KCVPIXELFORMATTYPE_444YPCBCR8BIPLANARVIDEORANGE 1
#endif
