// HAVE_EXPLICIT_MEMSET : BUILD2_AUTOCONF_LIBC_VERSION

#ifndef BUILD2_AUTOCONF_LIBC_VERSION
#  error BUILD2_AUTOCONF_LIBC_VERSION appears to be conditionally included
#endif

#undef HAVE_EXPLICIT_MEMSET

/* Since NetBSD 7.0.0.
 */
#if BUILD2_AUTOCONF_NETBSD_PREREQ(7, 0)
#  define HAVE_EXPLICIT_MEMSET 1
#endif
