// HAVE_KCVIMAGEBUFFERTRANSFERFUNCTION_SMPTE_ST_428_1 : BUILD2_AUTOCONF_LIBC_VERSION

#ifndef BUILD2_AUTOCONF_LIBC_VERSION
#  error BUILD2_AUTOCONF_LIBC_VERSION appears to be conditionally included
#endif

#undef HAVE_KCVIMAGEBUFFERTRANSFERFUNCTION_SMPTE_ST_428_1

/* SMPTE ST 428-1 transfer function, used in digital cinema.
 * Since MacOS 10.12/iOS 10
 */
#if BUILD2_AUTOCONF_MACOS_PREREQ(10, 12)
#  define HAVE_KCVIMAGEBUFFERTRANSFERFUNCTION_SMPTE_ST_428_1 1
#endif
